<?xml version="1.0" encoding="utf-8"?>
<!-- EN-Revision: 14767af0f05dffa6fdb9b49e1a1f4e9ca7022a60 Maintainer: rjhdby Status: ready -->
<!-- Reviewed: no -->
<reference xml:id="class.typeerror" role="exception" xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude">
 <title>Ошибка TypeError</title>
 <titleabbrev>TypeError</titleabbrev>

 <partintro>

  <!-- {{{ Error intro -->
  <section xml:id="typeerror.intro">
   &reftitle.intro;
   <para>
    Ошибка <classname>TypeError</classname> возникает, если:
    <simplelist>
     <member>
      Значение, которое устанавливают для свойства класса, не соответствует
      объявленному типу свойства.
     </member>
     <member>
      Тип аргумента, который передали в функцию, не соответствует типу,
      который для этого аргумента объявили в функции.
     </member>
     <member>
      Тип значения, которое вернула функция, не соответствует типу возврата,
      который объявили в функции.
     </member>
    </simplelist>
   </para>
  </section>
  <!-- }}} -->

  <section xml:id="typeerror.synopsis">
   &reftitle.classsynopsis;

<!-- {{{ Synopsis -->
   <classsynopsis class="class">
    <ooexception>
     <exceptionname>TypeError</exceptionname>
    </ooexception>

    <ooclass>
     <modifier>extends</modifier>
     <classname>Error</classname>
    </ooclass>

    <classsynopsisinfo role="comment">&InheritedProperties;</classsynopsisinfo>
    <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('class.error')/db:partintro/db:section/db:classsynopsis/db:fieldsynopsis[preceding-sibling::db:classsynopsisinfo[1][@role='comment' and text()='&Properties;']]))">
     <xi:fallback/>
    </xi:include>

    <classsynopsisinfo role="comment">&InheritedMethods;</classsynopsisinfo>
    <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('class.error')/db:refentry/db:refsect1[@role='description']/descendant::db:constructorsynopsis[@role='Error'])">
     <xi:fallback/>
    </xi:include>
    <xi:include xpointer="xmlns(db=http://docbook.org/ns/docbook) xpointer(id('class.error')/db:refentry/db:refsect1[@role='description']/descendant::db:methodsynopsis[@role='Error'])">
     <xi:fallback/>
    </xi:include>
   </classsynopsis>

<!-- }}} -->

  </section>

  <section xml:id="typeerror.changelog" role="changelog">
   &reftitle.changelog;
   <informaltable>
    <tgroup cols="2">
     <thead>
      <row>
       <entry>&Version;</entry>
       <entry>&Description;</entry>
      </row>
     </thead>
     <tbody>
      <row>
       <entry>7.1.0</entry>
       <entry>
        Ошибка <classname>TypeError</classname> больше не возникает в строгом режиме
        при передаче во встроенную PHP-функцию неправильного количества аргументов.
        Вместо этого выбрасывается ошибка <classname>ArgumentCountError</classname>.
       </entry>
      </row>
     </tbody>
    </tgroup>
   </informaltable>
  </section>

 </partintro>
</reference>
<!-- Keep this comment at the end of the file
Local variables:
mode: sgml
sgml-omittag:t
sgml-shorttag:t
sgml-minimize-attributes:nil
sgml-always-quote-attributes:t
sgml-indent-step:1
sgml-indent-data:t
indent-tabs-mode:nil
sgml-parent-document:nil
sgml-default-dtd-file:"~/.phpdoc/manual.ced"
sgml-exposed-tags:nil
sgml-local-catalogs:nil
sgml-local-ecat-files:nil
End:
vim600: syn=xml fen fdm=syntax fdl=2 si
vim: et tw=78 syn=sgml
vi: ts=1 sw=1
-->
